ALL_MIRROR = False
ALL_BLACK = False
ALL_WHITE = False
MAX_DEPTH = 10
N_PATHTRACE = 1
SS_DIM = 1
IMG_WIDTH = 2000

LIGHT_POWER = 21.0
ENV_LIGHT_POWER = 0.3

EPSILON = 1e-7

SHAPE_CUBE = 0
SHAPE_SPHERE = 1
SHAPE_CYLINDER = 2
SHAPE_EGG = 3
SHAPE_ROUND_CUBE = 4
SHAPE_STICKER = 5

EGG_R = 213 / 255
EGG_G = 126 / 255
EGG_B = 93 / 255

if ALL_MIRROR or ALL_WHITE:
    EGG_R = 1.0
    EGG_G = 1.0
    EGG_B = 1.0
elif ALL_BLACK:
    EGG_R = 0.0
    EGG_G = 0.0
    EGG_B = 0.0

ROUND_CUBE_R = 1.0
ROUND_CUBE_G = 1.0
ROUND_CUBE_B = 1.0

LIGHT_SAMPLES_PER_CELL = 4
LIGHT_Y = 105.0
LIGHT_LEN_X = 58.0
LIGHT_LEN_Z = 44.0
LIGHT_NX = 6
LIGHT_NZ = int(LIGHT_NX * LIGHT_LEN_Z / LIGHT_LEN_X)
CELL_SIZE_X = LIGHT_LEN_X / LIGHT_NX
CELL_SIZE_Z = LIGHT_LEN_Z / LIGHT_NZ
